--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/AIPTU/MyNotes
branches:
- master
projects:
  MyNotes:
    path: ""
    libs:
      - src: LatamPMDevs/FormAPI/libFormAPI
        version: ^2.1.1
      - src: poggit/libasynql/libasynql
        version: ^4.2.3
...
