name: MyNotes
version: 1.0.0
main: aiptu\mynotes\MyNotes
api: [5.0.0]
author: AIPTU
commands:
  notes:
    description: Opens the main menu for managing notes.
    permission: mynotes.command
permissions:
  mynotes.command:
    description: Allows the player to use the `/notes` command.
    default: true
